
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rageeb
 */
public class calculatorForm extends javax.swing.JFrame {

    /**
     * Creates new form calculatorForm
     */
    public calculatorForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstNumberLabel = new javax.swing.JLabel();
        secondNumberLabel = new javax.swing.JLabel();
        firstNumberField = new javax.swing.JTextField();
        secondNumberField = new javax.swing.JTextField();
        plusButton = new javax.swing.JButton();
        minusButton = new javax.swing.JButton();
        multiplyButton = new javax.swing.JButton();
        divideButton = new javax.swing.JButton();
        introLabel = new javax.swing.JLabel();
        resultLabel = new javax.swing.JLabel();
        exponentButton = new javax.swing.JButton();
        squareRootButton = new javax.swing.JButton();
        logButton = new javax.swing.JButton();
        percentageButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        firstNumberLabel.setText("First Number");

        secondNumberLabel.setText("Second Number");

        firstNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNumberFieldActionPerformed(evt);
            }
        });

        secondNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondNumberFieldActionPerformed(evt);
            }
        });

        plusButton.setText("+");
        plusButton.setToolTipText("Add");
        plusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButtonActionPerformed(evt);
            }
        });

        minusButton.setText("-");
        minusButton.setToolTipText("Subtract");
        minusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusButtonActionPerformed(evt);
            }
        });

        multiplyButton.setText("x");
        multiplyButton.setToolTipText("Multiplication");
        multiplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyButtonActionPerformed(evt);
            }
        });

        divideButton.setText("/");
        divideButton.setToolTipText("Division");
        divideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideButtonActionPerformed(evt);
            }
        });

        introLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        introLabel.setText("Rageeb's Calculator");
        introLabel.setToolTipText("");

        resultLabel.setFont(new java.awt.Font("Optima", 1, 18)); // NOI18N
        resultLabel.setText("The Answer Is: ");

        exponentButton.setText("EXP");
        exponentButton.setToolTipText("Raise First Number to the power of the Second Number");
        exponentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exponentButtonActionPerformed(evt);
            }
        });

        squareRootButton.setText("SQR");
        squareRootButton.setToolTipText("Find the Square Root Of The First Number");
        squareRootButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squareRootButtonActionPerformed(evt);
            }
        });

        logButton.setText("LOG");
        logButton.setToolTipText("Find The Logarithm Of The First Number by The Base, which is the Second Number");
        logButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logButtonActionPerformed(evt);
            }
        });

        percentageButton.setText("PCT");
        percentageButton.setToolTipText("The first number as a percentage of the second number");
        percentageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentageButtonActionPerformed(evt);
            }
        });

        clearButton.setText("CE");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstNumberLabel)
                    .addComponent(secondNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(secondNumberLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(introLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(exponentButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(squareRootButton)
                        .addGap(18, 18, 18)
                        .addComponent(logButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(plusButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(minusButton)
                        .addGap(18, 18, 18)
                        .addComponent(multiplyButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(divideButton)
                    .addComponent(percentageButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(clearButton)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(introLabel)
                .addGap(40, 40, 40)
                .addComponent(firstNumberLabel)
                .addGap(18, 18, 18)
                .addComponent(firstNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(secondNumberLabel)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)))
                .addComponent(secondNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(plusButton)
                            .addComponent(minusButton)
                            .addComponent(multiplyButton)
                            .addComponent(divideButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(exponentButton)
                            .addComponent(squareRootButton)
                            .addComponent(logButton)
                            .addComponent(percentageButton))
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clearButton)
                        .addGap(52, 52, 52))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void plusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButtonActionPerformed
        double numberOne, numberTwo;
        try {
            numberOne = Double.parseDouble(this.firstNumberField.getText());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please Enter a number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            numberTwo = Double.parseDouble(this.secondNumberField.getText());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please Enter a number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }  
        double r = numberOne + numberTwo;
        String result = String.format("%.2f", r);
        this.resultLabel.setText("The Answer Is: " + result);
    }//GEN-LAST:event_plusButtonActionPerformed

    private void minusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusButtonActionPerformed
        double numberOne, numberTwo;
        try {
            numberOne = Double.parseDouble(this.firstNumberField.getText());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please Enter a number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            numberTwo = Double.parseDouble(this.secondNumberField.getText());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please Enter a number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }  
        double r = numberOne - numberTwo;
        String result = String.format("%.2f", r);
        this.resultLabel.setText("The Answer Is: " + result);
    }//GEN-LAST:event_minusButtonActionPerformed

    private void firstNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNumberFieldActionPerformed
        
    }//GEN-LAST:event_firstNumberFieldActionPerformed

    private void secondNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secondNumberFieldActionPerformed

    private void multiplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyButtonActionPerformed
        double numberOne, numberTwo;
        try {
            numberOne = Double.parseDouble(this.firstNumberField.getText());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please Enter a number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            numberTwo = Double.parseDouble(this.secondNumberField.getText());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please Enter a number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }  
        double r = numberOne * numberTwo;
        String result = String.format("%.2f", r);
        this.resultLabel.setText("The Answer Is: " + result);
    }//GEN-LAST:event_multiplyButtonActionPerformed

    private void divideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideButtonActionPerformed
        double numberOne, numberTwo;
        try {
            numberOne = Double.parseDouble(this.firstNumberField.getText());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please Enter a number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            numberTwo = Double.parseDouble(this.secondNumberField.getText());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please Enter a number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }  
        double r = numberOne / numberTwo;
        String result = String.format("%.2f", r);
        this.resultLabel.setText("The Answer Is: " + result);
    }//GEN-LAST:event_divideButtonActionPerformed

    private void exponentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exponentButtonActionPerformed
        double numberOne, numberTwo;
        try {
            numberOne = Double.parseDouble(this.firstNumberField.getText());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please Enter a number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            numberTwo = Double.parseDouble(this.secondNumberField.getText());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please Enter a number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }  
        double r = Math.pow(numberTwo, numberTwo);
        String result = String.format("%.2f", r);
        this.resultLabel.setText("The Answer Is: " + result);
    }//GEN-LAST:event_exponentButtonActionPerformed

    private void squareRootButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squareRootButtonActionPerformed
        double numberOne, numberTwo;
        try {
            numberOne = Double.parseDouble(this.firstNumberField.getText());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please Enter a number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            numberTwo = Double.parseDouble(this.secondNumberField.getText());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please Enter a number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }  
        double r = Math.sqrt(numberOne);
        String result = String.format("%.2f", r);
        this.resultLabel.setText("The Answer Is: " + result);
    }//GEN-LAST:event_squareRootButtonActionPerformed

    private void logButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logButtonActionPerformed
        double numberOne, numberTwo;
        try {
            numberOne = Double.parseDouble(this.firstNumberField.getText());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please Enter a number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            numberTwo = Double.parseDouble(this.secondNumberField.getText());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please Enter a number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }  
        double r = Math.log(numberOne)/Math.log(numberTwo);
        String result = String.format("%.2f", r);
        this.resultLabel.setText("The Answer Is: " + result);
    }//GEN-LAST:event_logButtonActionPerformed

    private void percentageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentageButtonActionPerformed
        double numberOne, numberTwo;
        try {
            numberOne = Double.parseDouble(this.firstNumberField.getText());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please Enter a number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            numberTwo = Double.parseDouble(this.secondNumberField.getText());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please Enter a number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }  
        double r = (numberOne / numberTwo) * 100;
        String result = String.format("%.2f", r);
        this.resultLabel.setText("The Answer Is: " + result);
    }//GEN-LAST:event_percentageButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        firstNumberField.setText("");
        secondNumberField.setText("");
        resultLabel.setText("The Answer Is: ");
    }//GEN-LAST:event_clearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculatorForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JButton divideButton;
    private javax.swing.JButton exponentButton;
    private javax.swing.JTextField firstNumberField;
    private javax.swing.JLabel firstNumberLabel;
    private javax.swing.JLabel introLabel;
    private javax.swing.JButton logButton;
    private javax.swing.JButton minusButton;
    private javax.swing.JButton multiplyButton;
    private javax.swing.JButton percentageButton;
    private javax.swing.JButton plusButton;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JTextField secondNumberField;
    private javax.swing.JLabel secondNumberLabel;
    private javax.swing.JButton squareRootButton;
    // End of variables declaration//GEN-END:variables
}
